### ISSUE TITLE
Выцеплять текст из /балабоба

### ISSUE THREAD

**Issue by ksusonic** [MomHackers/MH-bot#18]
вызвается messages_processor.process_command(command, message) , и текст за исключением /yalm не попадает в generate балабобы

**Comment by ksusonic** [comment]
```
@2021-07-31T10:17:46.710438+00:00 app[bot.1]: INFO:seararules:Match (?i)\/yalm|(?i)\/балабоба
2021-07-31T10:17:46.710554+00:00 app[bot.1]: INFO:messagesprocessor:Entered /yalm command
2021-07-31T10:17:46.958158+00:00 app[bot.1]: ERROR:balaboba:Expecting value: line 1 column 1 (char 0)
2021-07-31T10:17:46.958159+00:00 app[bot.1]: Traceback (most recent call last):
2021-07-31T10:17:46.958160+00:00 app[bot.1]:   File "/app/bot/balaboba.py", line 33, in generate
2021-07-31T10:17:46.958160+00:00 app[bot.1]:     response = dict(json.loads(result))
2021-07-31T10:17:46.958162+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/json/__init__.py", line 346, in loads
2021-07-31T10:17:46.958162+00:00 app[bot.1]:     return _default_decoder.decode(s)
2021-07-31T10:17:46.958163+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 337, in decode
2021-07-31T10:17:46.958163+00:00 app[bot.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-07-31T10:17:46.958164+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
2021-07-31T10:17:46.958165+00:00 app[bot.1]:     raise JSONDecodeError("Expecting value", s, err.value) from None
2021-07-31T10:17:46.958165+00:00 app[bot.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-31T10:17:46.958232+00:00 app[bot.1]: INFO:messagesprocessor:Returning /yalm value
2021-07-31T10:17:47.045918+00:00 app[bot.1]: ERROR:vkbottle:
2021-07-31T10:17:47.045925+00:00 app[bot.1]: Traceback (most recent call last):
2021-07-31T10:17:47.045927+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/dispatch/bot_router.py", line 20, in route
2021-07-31T10:17:47.045927+00:00 app[bot.1]:     await view.handle_event(event, ctx_api, self.state_dispenser)
2021-07-31T10:17:47.045928+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/dispatch/views/bot/message.py", line 64, in handle_event
2021-07-31T10:17:47.045929+00:00 app[bot.1]:     handler_response = await handler.handle(message, **context_variables)
2021-07-31T10:17:47.045929+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/dispatch/handlers/from_func_handler.py", line 26, in handle
2021-07-31T10:17:47.045930+00:00 app[bot.1]:     return await self.handler(event, **context)
2021-07-31T10:17:47.045930+00:00 app[bot.1]:   File "/app/bot/main.py", line 70, in commands_handler
2021-07-31T10:17:47.045931+00:00 app[bot.1]:     await message.answer(
2021-07-31T10:17:47.045932+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/tools/dev_tools/mini_types/bot/message.py", line 55, in answer
2021-07-31T10:17:47.045932+00:00 app[bot.1]:     return (await self.ctx_api.request("messages.send", data))["response"]
2021-07-31T10:17:47.045933+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/api/api.py", line 54, in request
2021-07-31T10:17:47.045933+00:00 app[bot.1]:     return await self.validate_response(method, data, response)
2021-07-31T10:17:47.045933+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/api/api.py", line 79, in validate_response
2021-07-31T10:17:47.045934+00:00 app[bot.1]:     response = await validator.validate(method, data, response, self)
2021-07-31T10:17:47.045935+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/vkbottle/api/response_validator/vk_api_error_validator.py", line 31, in validate
2021-07-31T10:17:47.045935+00:00 app[bot.1]:     raise VKAPIError(code, msg, response)
2021-07-31T10:17:47.045936+00:00 app[bot.1]: abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: message is empty or invalid
```

**Comment by ksusonic** [comment]
@searayeah нид хелп
